/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaCadastro.java
 *
 * Created on 28/03/2012, 14:58:53
 */
package br.ucb.gui;

import br.ucb.beans.Usuario;
import br.ucb.constants.Constants;
import br.ucb.dao.UsuarioDAO;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author GUICUNHA
 */
public class TelaExcluiUsuario extends javax.swing.JFrame {

    private Usuario usuario;
    private TelaUsuarios telaUsers;
    
    public TelaExcluiUsuario(TelaUsuarios telaUsers) {
        int selectedIndex = telaUsers.getjList1().getSelectedIndex();
        setUsuario((Usuario) telaUsers.getjList1().getModel().getElementAt(selectedIndex));
        setTelaUsers(telaUsers);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Excluir = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        UniversidadeLabel = new javax.swing.JLabel();
        LoginLabel = new javax.swing.JLabel();
        universidadeTextField = new javax.swing.JTextField(getUsuario().getLogin());
        NomeLabel = new javax.swing.JLabel();
        NomeLabel1 = new javax.swing.JLabel();
        tipoUsuarioTextField = new javax.swing.JTextField(getUsuario().getLogin());
        loginTextField = new javax.swing.JTextField(getUsuario().getLogin());
        nomeTextField = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setTitle("EXCLUSÃO - Corpus Generator");
        setResizable(false);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.darkGray));

        Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ucb/img/salvar.png"))); // NOI18N
        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ucb/img/limpar.png"))); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ucb/img/logon_cg.jpg"))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados:"));

        UniversidadeLabel.setText("Universidade :");

        LoginLabel.setText("Login :");

        universidadeTextField.setEditable(false);
        universidadeTextField.setText(getUsuario().getUniversidade());

        NomeLabel.setText("Nome : ");

        NomeLabel1.setText("Tipo de usuário : ");

        tipoUsuarioTextField.setEditable(false);
        tipoUsuarioTextField.setText(getUsuario().getTipoUsuario() == Constants.COORDENADOR ? "Coordenador" : "Equipe");

        loginTextField.setEditable(false);
        loginTextField.setText(getUsuario().getLogin());

        nomeTextField.setEditable(false);
        nomeTextField.setText(getUsuario().getNome());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginLabel)
                            .addComponent(UniversidadeLabel)
                            .addComponent(NomeLabel))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(NomeLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoUsuarioTextField)
                    .addComponent(universidadeTextField)
                    .addComponent(loginTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeTextField))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(UniversidadeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoginLabel)
                            .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(universidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel1)
                    .addComponent(tipoUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cancelar)
                .addGap(13, 13, 13))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel5)
                .addContainerGap(151, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar))
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-446)/2, (screenSize.height-486)/2, 446, 486);
    }// </editor-fold>//GEN-END:initComponents

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        if(UsuarioDAO.excluiUsuario(getUsuario())){
            this.dispose();
            getTelaUsers().dispose();
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaCadastroUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Excluir;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JLabel NomeLabel1;
    private javax.swing.JLabel UniversidadeLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField tipoUsuarioTextField;
    private javax.swing.JTextField universidadeTextField;
    // End of variables declaration//GEN-END:variables

    public JTextField getLoginTextField() {
        return universidadeTextField;
    }

    public void setLoginTextField(JTextField LoginTextField) {
        this.universidadeTextField = LoginTextField;
    }

    public void setSenhaPasswordField(JPasswordField senhaPasswordField) {
        this.nomeTextField = senhaPasswordField;
    }

    public JButton getExcluir() {
        return Excluir;
    }

    public void setExcluir(JButton Excluir) {
        this.Excluir = Excluir;
    }

    /**
     * @return the Cancelar
     */
    public javax.swing.JButton getCancelar() {
        return Cancelar;
    }

    /**
     * @param Cancelar the Cancelar to set
     */
    public void setCancelar(javax.swing.JButton Cancelar) {
        this.Cancelar = Cancelar;
    }

    /**
     * @return the LoginLabel
     */
    public javax.swing.JLabel getLoginLabel() {
        return LoginLabel;
    }

    /**
     * @param LoginLabel the LoginLabel to set
     */
    public void setLoginLabel(javax.swing.JLabel LoginLabel) {
        this.LoginLabel = LoginLabel;
    }

    /**
     * @return the NomeLabel
     */
    public javax.swing.JLabel getNomeLabel() {
        return NomeLabel;
    }

    /**
     * @param NomeLabel the NomeLabel to set
     */
    public void setNomeLabel(javax.swing.JLabel NomeLabel) {
        this.NomeLabel = NomeLabel;
    }

    /**
     * @return the UniversidadeLabel
     */
    public javax.swing.JLabel getUniversidadeLabel() {
        return UniversidadeLabel;
    }

    /**
     * @param UniversidadeLabel the UniversidadeLabel to set
     */
    public void setUniversidadeLabel(javax.swing.JLabel UniversidadeLabel) {
        this.UniversidadeLabel = UniversidadeLabel;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @param jLabel5 the jLabel5 to set
     */
    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public void setNomeTextField(JPasswordField nomeTextField) {
        this.nomeTextField = nomeTextField;
    }

    public JTextField getTipoUsuarioTextField() {
        return tipoUsuarioTextField;
    }

    public void setTipoUsuarioTextField(JTextField tipoUsuarioTextField) {
        this.tipoUsuarioTextField = tipoUsuarioTextField;
    }

    public JTextField getUniversidadeTextField() {
        return universidadeTextField;
    }

    public void setUniversidadeTextField(JTextField universidadeTextField) {
        this.universidadeTextField = universidadeTextField;
    }
    
    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public TelaUsuarios getTelaUsers() {
        return telaUsers;
    }

    public void setTelaUsers(TelaUsuarios telaUsers) {
        this.telaUsers = telaUsers;
    }
}
